# 第一课：PyTorch 张量（Tensor）基础

## 什么是张量？

张量是深度学习中最基本的数据结构：

| 概念 | 维度 | 示例 |
|------|------|------|
| 标量 | 0维 | `5` |
| 向量 | 1维 | `[1, 2, 3]` |
| 矩阵 | 2维 | `[[1, 2], [3, 4]]` |
| 高维张量 | 3维+ | 图片 `(C, H, W)`，批量图片 `(B, C, H, W)` |

PyTorch 的 Tensor 类似 NumPy 的 ndarray，但**可以在 GPU 上运行**，且支持**自动求导**。

In [1]:
import torch
import numpy as np

## 1. 张量的创建

In [2]:
# 从 Python 列表创建
a = torch.tensor([1, 2, 3, 4, 5])
print("从列表创建:", a)
print("维度:", a.dim(), "形状:", a.shape, "数据类型:", a.dtype)

从列表创建: tensor([1, 2, 3, 4, 5])
维度: 1 形状: torch.Size([5]) 数据类型: torch.int64


In [3]:
# 从 NumPy 数组创建（共享内存！））
np_array = np.array([1.0, 2.0, 3.0])
b = torch.from_numpy(np_array)
print("从 NumPy 创建:", b)

# Tensor 转 NumPy
c = b.numpy()
print("Tensor 转 NumPy:", c, type(c))

# 共享内存演示：修改一个，另一个也会变
np_array[0] = 999
print("修改 np_array 后，tensor b 也变了:", b)

从 NumPy 创建: tensor([1., 2., 3.], dtype=torch.float64)
Tensor 转 NumPy: [1. 2. 3.] <class 'numpy.ndarray'>
修改 np_array 后，tensor b 也变了: tensor([999.,   2.,   3.], dtype=torch.float64)


In [5]:
# 创建特殊张量
zeros = torch.zeros(3, 4)       # 全零
ones = torch.ones(2, 3)         # 全一
empty = torch.empty(2, 2)       # 未初始化（值随机）
rand = torch.rand(3, 3)         # 均匀分布 [0, 1)
randn = torch.randn(3, 3)       # 标准正态分布 N(0, 1)
arange = torch.arange(0, 10, 2) # 等差数列 [0, 2, 4, 6, 8]
linspace = torch.linspace(0, 1, 5)  # 等间隔

print("全零张量:\n", zeros)
print("全一张量:\n", ones)
print("未初始化张量:\n", empty)
print("随机张量:\n", rand)
print("随机正态分布张量:\n", randn)
print("等差数列:", arange)
print("等间隔:", linspace)

全零张量:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
全一张量:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
未初始化张量:
 tensor([[2.3694e-38, 2.3694e-38],
        [1.4013e-45, 0.0000e+00]])
随机张量:
 tensor([[0.2428, 0.2822, 0.1420],
        [0.8589, 0.4783, 0.2003],
        [0.3819, 0.7607, 0.8318]])
随机正态分布张量:
 tensor([[ 0.6174,  0.1401, -1.7326],
        [-0.8522,  1.4334,  0.3790],
        [ 2.0698, -1.1297,  1.5898]])
等差数列: tensor([0, 2, 4, 6, 8])
等间隔: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [14]:
print("随机张量:\n", torch.rand(2, 2, 3, 4))

随机张量:
 tensor([[[[0.7640, 0.3750, 0.4914, 0.7451],
          [0.6162, 0.1761, 0.5089, 0.9172],
          [0.4965, 0.0857, 0.2799, 0.3675]],

         [[0.2539, 0.0104, 0.5140, 0.3061],
          [0.4256, 0.2440, 0.9624, 0.6481],
          [0.9331, 0.3833, 0.7757, 0.2689]]],


        [[[0.3634, 0.2487, 0.1206, 0.1866],
          [0.8814, 0.3353, 0.6492, 0.6952],
          [0.5908, 0.9276, 0.5881, 0.6317]],

         [[0.2113, 0.7126, 0.8736, 0.0913],
          [0.7577, 0.6865, 0.9884, 0.7757],
          [0.0809, 0.3192, 0.3129, 0.4608]]]])


In [6]:
# 指定数据类型
d = torch.tensor([1, 2, 3], dtype=torch.float32)
e = torch.tensor([1.5, 2.7], dtype=torch.int32)  # 会截断小数
print("float32:", d, d.dtype)
print("int32:", e, e.dtype)

# 类型转换
f = d.to(torch.float16)  # 半精度，在深度学习中常用于节省显存
print("float16:", f, f.dtype)

float32: tensor([1., 2., 3.]) torch.float32
int32: tensor([1, 2], dtype=torch.int32) torch.int32
float16: tensor([1., 2., 3.], dtype=torch.float16) torch.float16


## 2. 张量的运算

In [7]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

# 逐元素运算
print("加法:", x + y)
print("减法:", x - y)
print("逐元素乘法:", x * y)     # 注意：这不是矩阵乘法！
print("除法:", x / y)
print("幂运算:", x ** 2)

# 张量与标量运算
print("标量加法:", x + 10)
print("标量乘法:", x * 2)

加法: tensor([5., 7., 9.])
减法: tensor([-3., -3., -3.])
逐元素乘法: tensor([ 4., 10., 18.])
除法: tensor([0.2500, 0.4000, 0.5000])
幂运算: tensor([1., 4., 9.])
标量加法: tensor([11., 12., 13.])
标量乘法: tensor([2., 4., 6.])


In [8]:
# 常用数学函数
x = torch.tensor([1.0, 2.0, 3.0])
print("求和:", x.sum())
print("求均值:", x.mean())
print("求最大值:", x.max())
print("求最小值:", x.min())
print("求绝对值:", torch.abs(torch.tensor([-1.0, -2.0, 3.0])))
print("求平方根:", torch.sqrt(x))
print("求指数:", torch.exp(x))

求和: tensor(6.)
求均值: tensor(2.)
求最大值: tensor(3.)
求最小值: tensor(1.)
求绝对值: tensor([1., 2., 3.])
求平方根: tensor([1.0000, 1.4142, 1.7321])
求指数: tensor([ 2.7183,  7.3891, 20.0855])


In [10]:
# 矩阵运算
A = torch.randn(3, 4)
B = torch.randn(4, 2)
print("A:\n", A)
print("B:\n", B)
print("矩阵乘法 A@B:\n", A @ B)           # 推荐：@ 运算符
print("矩阵乘法 matmul:\n", torch.matmul(A, B))  # 等价写法
print("转置 A^T:\n", A.T)
print("A 的形状:", A.shape, "A^T 的形状:", A.T.shape)

A:
 tensor([[-1.9236, -0.1514,  0.6725, -1.4537],
        [ 0.1853,  0.2811,  0.4052, -0.6023],
        [-0.3500,  0.0037, -2.6764,  1.1405]])
B:
 tensor([[-0.1115, -0.2582],
        [-0.2349, -0.6751],
        [ 1.6308,  0.1632],
        [ 1.1508,  0.3867]])
矩阵乘法 A@B:
 tensor([[-0.3261,  0.1465],
        [-0.1190, -0.4044],
        [-3.0140,  0.0921]])
矩阵乘法 matmul:
 tensor([[-0.3261,  0.1465],
        [-0.1190, -0.4044],
        [-3.0140,  0.0921]])
转置 A^T:
 tensor([[-1.9236,  0.1853, -0.3500],
        [-0.1514,  0.2811,  0.0037],
        [ 0.6725,  0.4052, -2.6764],
        [-1.4537, -0.6023,  1.1405]])
A 的形状: torch.Size([3, 4]) A^T 的形状: torch.Size([4, 3])


## 3. 广播机制（Broadcasting）

当两个张量形状不同时，PyTorch 会自动"扩展"较小的张量，使其形状匹配后再运算。

广播规则：
1. 从最右边的维度开始比较
2. 两个维度相等，或者其中一个为1，才能广播
3. 缺失的维度视为1

In [17]:
# 形状 (3,) + 形状 (1,) → (3,)
a1 = torch.tensor([1.0, 2.0, 3.0])
b1 = torch.tensor([10.0])
print("a1:", a1.shape)
print("b1:", b1.shape)
print("广播 (3,) + (1,):", a1 + b1)

# 形状 (3, 4) + 形状 (4,) → 每行都加上同一个向量
a2 = torch.ones(3, 4)
b2 = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("广播 (3,4) + (4,):\n", a2 + b2)

# 形状 (3, 1) + 形状 (1, 4) → (3, 4)
a3 = torch.arange(3).float().reshape(3, 1)  # [[0],[1],[2]]
b3 = torch.arange(4).float().reshape(1, 4)  # [[0,1,2,3]]
print("广播 (3,1) + (1,4):\n", a3 + b3)

a1: torch.Size([3])
b1: torch.Size([1])
广播 (3,) + (1,): tensor([11., 12., 13.])
广播 (3,4) + (4,):
 tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]])
广播 (3,1) + (1,4):
 tensor([[0., 1., 2., 3.],
        [1., 2., 3., 4.],
        [2., 3., 4., 5.]])


## 4. 索引与切片

In [15]:
t = torch.arange(12).reshape(3, 4)
print("原始张量:\n", t)
print("第0行:", t[0])
print("第1列:", t[:, 1])
print("第0-1行:", t[0:2])
print("第1行第2列的元素:", t[1, 2])

# 用布尔索引
mask = t > 5
print("大于5的元素:", t[mask])

# 高级索引：选择特定行和列
print("取第0行和第2行的第1列和第3列:", t[[0, 2], [1, 3]])

原始张量:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
第0行: tensor([0, 1, 2, 3])
第1列: tensor([1, 5, 9])
第0-1行: tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
第1行第2列的元素: tensor(6)
大于5的元素: tensor([ 6,  7,  8,  9, 10, 11])
取第0行和第2行的第1列和第3列: tensor([ 1, 11])


## 5. 形状操作

In [18]:
x = torch.arange(12)
print("原始:", x.shape)

# reshape：改变形状（不改变数据）
print("reshape (3,4):\n", x.reshape(3, 4))
print("reshape (2,6):\n", x.reshape(2, 6))

# view：与 reshape 类似，但要求内存连续
print("view (4,3):\n", x.view(4, 3))

# -1 表示自动推断
print("reshape (2, -1):\n", x.reshape(2, -1))  # 自动算出列为6

原始: torch.Size([12])
reshape (3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
reshape (2,6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
view (4,3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
reshape (2, -1):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
# squeeze / unsqueeze：增加或去除大小为1的维度
y = x.reshape(3, 1, 4)
print("原始形状:", y.shape)
print("squeeze 去除1维:", y.squeeze().shape)
print(y)
print("unsqueeze 增加维度:", x.unsqueeze(0).shape)  # (12,) → (1, 12)

print("unsqueeze 在dim=1:", x.unsqueeze(1).shape)    # (12,) → (12, 1)

原始形状: torch.Size([3, 1, 4])
squeeze 去除1维: torch.Size([3, 4])
unsqueeze 增加维度: torch.Size([1, 12])
unsqueeze 在dim=1: torch.Size([12, 1])


In [20]:
# permute：重排维度顺序
img = torch.randn(3, 224, 224)  # (C, H, W) - PyTorch 图片格式
print("原始图片形状:", img.shape)
print("permute 为 (H, W, C):", img.permute(1, 2, 0).shape)  # Matplotlib 需要的格式

原始图片形状: torch.Size([3, 224, 224])
permute 为 (H, W, C): torch.Size([224, 224, 3])


## 6. GPU 加速

In [21]:
print("CUDA 是否可用:", torch.cuda.is_available())

if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU 设备:", torch.cuda.get_device_name(0))

    # 将张量移到 GPU
    x_gpu = torch.randn(3, 3, device=device)
    print("GPU 上的张量:", x_gpu.device)

    # GPU ↔ CPU 互转
    x_cpu = x_gpu.cpu()
    print("移回 CPU:", x_cpu.device)

    # .to() 方法更通用
    x_to = torch.randn(3, 3).to(device)
    print("用 .to() 移到 GPU:", x_to.device)
else:
    print("当前环境没有 GPU，使用 CPU 即可。")
    print("在 Colab 中可以通过 '运行时 → 更改运行时类型 → GPU' 来启用 GPU。")

CUDA 是否可用: True
GPU 设备: NVIDIA GeForce RTX 5060 Ti
GPU 上的张量: cuda:0
移回 CPU: cpu
用 .to() 移到 GPU: cuda:0


In [24]:
# GPU vs CPU 速度对比
import time

size = 1000
a_cpu = torch.randn(size, size)
b_cpu = torch.randn(size, size)

start = time.time()
for _ in range(10000):
    c_cpu = a_cpu @ b_cpu
cpu_time = time.time() - start
print(f"CPU 矩阵乘法 10000 次耗时: {cpu_time:.4f} 秒")

if torch.cuda.is_available():
    a_gpu = a_cpu.to('cuda')
    b_gpu = b_cpu.to('cuda')

    start = time.time()
    for _ in range(10000):
        c_gpu = a_gpu @ b_gpu
    torch.cuda.synchronize()  # 等待 GPU 计算完成
    gpu_time = time.time() - start
    print(f"GPU 矩阵乘法 10000 次耗时: {gpu_time:.4f} 秒")
    print(f"GPU 加速比: {cpu_time / gpu_time:.1f}x")

CPU 矩阵乘法 10000 次耗时: 30.1744 秒
GPU 矩阵乘法 10000 次耗时: 1.7329 秒
GPU 加速比: 17.4x


## 7. 张量的拼接与拆分

In [25]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("cat 沿行拼接 (dim=0):\n", torch.cat([a, b], dim=0))
print("cat 沿列拼接 (dim=1):\n", torch.cat([a, b], dim=1))

# stack：在新维度上拼接
print("stack:\n", torch.stack([a, b], dim=0))  # (2, 2, 2)

cat 沿行拼接 (dim=0):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
cat 沿列拼接 (dim=1):
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
stack:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
# chunk / split：拆分
c = torch.arange(10)
print("chunk 拆成3份:", torch.chunk(c, 3))
print("split 按大小4拆分:", torch.split(c, 4))

## 8. 原地操作（In-place Operations）

以 `_` 后缀结尾的操作是原地操作，会直接修改原始张量。

⚠️ **注意**：原地操作在自动求导时可能导致问题，一般建议避免使用。

In [26]:
x = torch.tensor([1.0, 2.0, 3.0])
print("原始 x:", x)

x.add_(10)      # 原地加法
print("原地加法后:", x)

x.mul_(2)       # 原地乘法
print("原地乘法后:", x)

# 对比：非原地操作不会修改原始张量
y = torch.tensor([1.0, 2.0, 3.0])
z = y.add(10)   # 非原地，y 不变
print("y 不变:", y)
print("z 是新张量:", z)

原始 x: tensor([1., 2., 3.])
原地加法后: tensor([11., 12., 13.])
原地乘法后: tensor([22., 24., 26.])
y 不变: tensor([1., 2., 3.])
z 是新张量: tensor([11., 12., 13.])


---
## 📝 第一课总结

| 知识点 | 要点 |
|--------|------|
| 张量创建 | `torch.tensor()`, `zeros()`, `ones()`, `randn()`, `arange()` |
| 张量运算 | 逐元素运算 `+ - * /`，矩阵乘法 `@`，聚合 `sum() mean()` |
| 广播机制 | 形状不同时自动扩展，从最右维度开始比较 |
| 索引切片 | 与 NumPy 类似，支持布尔索引 |
| 形状操作 | `reshape()`, `view()`, `squeeze()`, `unsqueeze()`, `permute()` |
| GPU 加速 | `.to('cuda')`, `.cpu()`，GPU 对大规模矩阵运算加速显著 |
| 拼接拆分 | `cat()`, `stack()`, `chunk()`, `split()` |
| 原地操作 | 后缀 `_`，慎用，可能影响自动求导 |